pipeline:
  name: test-busted
  identifier: testbusted
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: busted
        build: <+input>
  stages:
    - stage:
        name: linux-amd64
        identifier: linuxamd64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Busted
                  identifier: Busted
                  spec:
                    uses: lunarmodules/busted@v2.1.2
        when:
          pipelineStatus: All
    - stage:
        name: linux-arm64
        identifier: linuxarm64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Busted
                  identifier: Busted
                  spec:
                    uses: lunarmodules/busted@v2.1.2
        when:
          pipelineStatus: All
    - stage:
        name: windows-amd64
        identifier: windowsamd64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Busted
                  identifier: Busted
                  spec:
                    uses: lunarmodules/busted@v2.1.2
        when:
          pipelineStatus: All
    - stage:
        name: windows-arm64
        identifier: windowsarm64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Busted
                  identifier: Busted
                  spec:
                    uses: lunarmodules/busted@v2.1.2
        when:
          pipelineStatus: All
